#include "physics.h"

namespace ChronoShift
{

  FLX_REFL_REGISTER_START(BoundingBox2D)
    FLX_REFL_REGISTER_PROPERTY(size)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(OnHover)
    FLX_REFL_REGISTER_PROPERTY(is_hovering)
    FLX_REFL_REGISTER_PROPERTY(on_enter)
    FLX_REFL_REGISTER_PROPERTY(on_exit)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(OnClick)
    FLX_REFL_REGISTER_PROPERTY(is_clicked)
  FLX_REFL_REGISTER_END;

}
