#include "Components.h"

namespace OpenGLRendering
{

  FLX_REFL_REGISTER_START(Transform)
    FLX_REFL_REGISTER_PROPERTY(transform)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Shader)
    FLX_REFL_REGISTER_PROPERTY(shader)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Texture)
    FLX_REFL_REGISTER_PROPERTY(texture)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Material)
    FLX_REFL_REGISTER_PROPERTY(diffuse)
    FLX_REFL_REGISTER_PROPERTY(specular)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Mesh)
    FLX_REFL_REGISTER_PROPERTY(vertices)
    FLX_REFL_REGISTER_PROPERTY(indices)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Camera)
    FLX_REFL_REGISTER_PROPERTY(target_position)
    FLX_REFL_REGISTER_PROPERTY(direction)
    FLX_REFL_REGISTER_PROPERTY(right)
    FLX_REFL_REGISTER_PROPERTY(up)
  FLX_REFL_REGISTER_END;

}