#include "Components.h"

namespace OpenGLRendering
{

  FLX_REFL_REGISTER_START(IsActive)
    FLX_REFL_REGISTER_PROPERTY(is_active)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(LocalPosition)
    FLX_REFL_REGISTER_PROPERTY(position)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(GlobalPosition)
    FLX_REFL_REGISTER_PROPERTY(position)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Rotation)
    FLX_REFL_REGISTER_PROPERTY(rotation)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Scale)
    FLX_REFL_REGISTER_PROPERTY(scale)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Transform)
    FLX_REFL_REGISTER_PROPERTY(is_dirty)
    FLX_REFL_REGISTER_PROPERTY(transform)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Shader)
    FLX_REFL_REGISTER_PROPERTY(shader)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Texture)
    FLX_REFL_REGISTER_PROPERTY(texture)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Material)
    FLX_REFL_REGISTER_PROPERTY(diffuse)
    FLX_REFL_REGISTER_PROPERTY(specular)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Mesh)
    FLX_REFL_REGISTER_PROPERTY(mesh)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Model)
    FLX_REFL_REGISTER_PROPERTY(model)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Camera)
    FLX_REFL_REGISTER_PROPERTY(is_dirty)
    FLX_REFL_REGISTER_PROPERTY(front)
    FLX_REFL_REGISTER_PROPERTY(right)
    FLX_REFL_REGISTER_PROPERTY(up)
    FLX_REFL_REGISTER_PROPERTY(world_up)
    FLX_REFL_REGISTER_PROPERTY(view)
    FLX_REFL_REGISTER_PROPERTY(projection)
    FLX_REFL_REGISTER_PROPERTY(perspective)
    FLX_REFL_REGISTER_PROPERTY(fov)
    FLX_REFL_REGISTER_PROPERTY(near)
    FLX_REFL_REGISTER_PROPERTY(far)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(DirectionalLight)
    FLX_REFL_REGISTER_PROPERTY(direction)
    FLX_REFL_REGISTER_PROPERTY(ambient)
    FLX_REFL_REGISTER_PROPERTY(diffuse)
    FLX_REFL_REGISTER_PROPERTY(specular)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(PointLight)
    FLX_REFL_REGISTER_PROPERTY(ambient)
    FLX_REFL_REGISTER_PROPERTY(diffuse)
    FLX_REFL_REGISTER_PROPERTY(specular)
  FLX_REFL_REGISTER_END;

}