#include "DemoComponents.h"

namespace FlexEditor
{

  FLX_REFL_REGISTER_START(IsAlive)
    FLX_REFL_REGISTER_PROPERTY(value)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Amount)
    FLX_REFL_REGISTER_PROPERTY(value)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Health)
    FLX_REFL_REGISTER_PROPERTY(value)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(Transform)
    FLX_REFL_REGISTER_PROPERTY(x)
    FLX_REFL_REGISTER_PROPERTY(y)
    FLX_REFL_REGISTER_PROPERTY(z)
  FLX_REFL_REGISTER_END;

}