#include "physics.h"
#include "Editor/componentviewer.h"

namespace ChronoDrift
{
  FLX_REFL_REGISTER_START(BoundingBox2D)
    FLX_REFL_REGISTER_PROPERTY(size)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(OnHover)
    FLX_REFL_REGISTER_PROPERTY(is_hovering)
    FLX_REFL_REGISTER_PROPERTY(on_enter)
    FLX_REFL_REGISTER_PROPERTY(on_exit)
  FLX_REFL_REGISTER_END;

  FLX_REFL_REGISTER_START(OnClick)
    FLX_REFL_REGISTER_PROPERTY(is_clicked)
  FLX_REFL_REGISTER_END;


  FLX_REFL_REGISTER_START(Rigidbody)
    FLX_REFL_REGISTER_PROPERTY(velocity)
    FLX_REFL_REGISTER_PROPERTY(is_static)
  FLX_REFL_REGISTER_END;

  COMPONENT_VIEWER_START(BoundingBox2D)
    COMPONENT_VIEWER_DRAG_VECTOR2(min)
    COMPONENT_VIEWER_DRAG_VECTOR2(max)
    COMPONENT_VIEWER_BOOL(isColliding)
  COMPONENT_VIEWER_END(BoundingBox2D)

  COMPONENT_VIEWER_START(OnHover)
    COMPONENT_VIEWER_BOOL(is_hovering)
    COMPONENT_VIEWER_BOOL(on_enter)
    COMPONENT_VIEWER_BOOL(on_exit)
  COMPONENT_VIEWER_END(OnHover)

  COMPONENT_VIEWER_START(OnClick)
    COMPONENT_VIEWER_BOOL(is_clicked)
  COMPONENT_VIEWER_END(OnClick)

  COMPONENT_VIEWER_START(Rigidbody)
    COMPONENT_VIEWER_DRAG_VECTOR2(velocity)
    COMPONENT_VIEWER_BOOL(is_static)
  COMPONENT_VIEWER_END(Rigidbody)

  void RegisterPhysicsComponents()
  {
    REGISTER_COMPONENT_VIEWER(BoundingBox2D);
    REGISTER_COMPONENT_VIEWER(OnHover);
    REGISTER_COMPONENT_VIEWER(OnClick);
    REGISTER_COMPONENT_VIEWER(Rigidbody);
  }
}
